### ISSUE TITLE
Not loading in Mac OS

### ISSUE THREAD

**Issue by officialgio** [ovasquez/docfx-material#17]
For some reason i keep getting warnings. After building and and getting into local host, it's redirecting me to the index page.

![image](https://github.com/ovasquez/docfx-material/assets/87216285/881b473c-0a1b-41dd-9730-343f23f325d3)

![image](https://github.com/ovasquez/docfx-material/assets/87216285/3d4d2980-d343-4bac-819d-f13c171a8efa)

![image](https://github.com/ovasquez/docfx-material/assets/87216285/b94fbde5-e918-41bb-924e-14c51abb0bf2)

**Comment by ovasquez** [comment]
@officialgio is this problem only happening when using the DocFX Material Theme? I can’t reproduce this issue in a local environment.

**Comment by filzrev** [comment]
From your screenshots.
It seems that docfx is installed using [`homebrew` package](https://formulae.brew.sh/formula/docfx). 

It's not officially supported.
And the `docfx` package of `homebrew` has problems that some steps to build `templates` content are missing. 
https://github.com/dotnet/docfx/issues/9081

Anyway, this problem is not relating to the `docfx-material' repository.
And it should be reported at https://github.com/Homebrew/homebrew-core

**Comment by ovasquez** [comment]
Thanks @filzrev for identifying the issue and correctly redirecting to the problem repo. I'm closing this issue as it's not related to docfx-material.
