### ISSUE TITLE
Warning:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates]There is no template processing document type(s): Conceptual,ManagedReference,Toc

### ISSUE THREAD

**Issue by frohlichcortezh** [ovasquez/docfx-material#8]
I've got this warning when build with this theme and the served website doesn't show it in material style.
I believed I've followed the instructions correctly. 
Have you already encounted this behavior ? Anything else I should have done ?

docfx.json

```
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/**.csproj"
          ],
          "cwd": "../.."
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "obj/**",
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "globalMetadataFiles": [],
    "fileMetadataFiles": [],
    "template": [
      "default",
      "templates/material"
  ],
    "postProcessors": [],
    "markdownEngineName": "markdig",
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

![image](https://user-images.githubusercontent.com/26347102/93574447-b8438780-f998-11ea-91dc-79fb78e901d3.png)

**Comment by frohlichcortezh** [comment]
I'm sorry, found the solution on the doc of DocFx:

https://dotnet.github.io/docfx/tutorial/howto_create_custom_template.html

Running ```docfx build docfx.json -t default,templates/material --serve``` solved the warning and I could see the website in material style.

**Comment by ovasquez** [comment]
Hey @frohlichcortezh, I know this issue is closed however I wanted to point out that you should not need that `-t` parameter in the command line if the `docfx.json` is configured properly.

I just tested the following on the latest DocFX version 2.56, and there were no warnings or errors when using the material template and using only `docfx --serve` or `docfx --build` from the root folder of the sample docs.
- Building a sample site with default settings (except the added template)
- Building the sample site using the `docfx.json` content that you added on the issue.

I would make sure that the DocFX version you're using is up to date, I couldn't reproduce the problem when using the template as described in the instructions.
